### ISSUE TITLE
Trans


### ISSUE THREAD

**Issue by kenti123** [SirReubs/Library-System#4]

**Comment by SirReubs** [comment]
You didn't leave any more info on what the issue was, but I'd just like to clarify that I'm aware of multiple issues in the program and I haven't had time to even open up my computer and fix these issues but I'll have it fixed in the near future.

**Comment by kenti123** [comment]
Tran?

**Comment by kenti123** [comment]
I'm sorry man trust me my bad

**Comment by kenti123** [comment]
Did I ruin ur code at level this? Hhahahhahaa []()![carlos.jpg](https://github.com/SirReubs/Library-System/assets/147777549/3cd06e2d-13af-4fbf-aa72-acbdc9d1007b)
